quwen:
  wx:
    app-id: wx56acef520e1b0030
    app-secret: 3848a4749c6337c86f3dcf42b3d21d2a
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://2wrf4s.natappfree.cc/wx/order/pay-notify
corey:
  ## by Zeng Hui，测试号的appid和appsecret和微信号
  wx:
    app-id: wx0ecc55fde07a32af
    app-secret: 204968f0b20dd9d7551eea63b797a459
    username: gh_5aebddaa55cc
  ##临时域名
  domain: http://dkh5p9.natappfree.cc

