quwen:
  wx:
    app-id: wx0ecc55fde07a32af
    app-secret: 204968f0b20dd9d7551eea63b797a459
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify
corey:
  ## by Zeng Hui，测试号的appid和appsecret和微信号
  wx:
    app-id: wx0ecc55fde07a32af
    app-secret: 204968f0b20dd9d7551eea63b797a459
    username: gh_5aebddaa55cc
  ##临时域名
  domain: http://192.168.199.105:8080
  domain2: http://4yy74u.natappfree.cc/

