spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newenergy?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: newenergy
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
           auto: update
  mail:
    host: smtp.qq.com
    username: 2359046280@qq.com
    password: jkutibhbjrgbebhf
    #    password: hgdr123456
    #    password: hgdr123


    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

backup:
  basedir: backup/

  username: newenergy
  password: 123456
  database: newenergy

  loadname: backup.sql
  encloadname: backup

  encnum: 0xCC


